#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from termcolor import colored


def main():

    # Ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./smile word")

    # Instantiate analyzer
    analyzer = Analyzer()

    # Analyze word
    score = analyzer.analyze(sys.argv[1])
    if score > 0.0:
        print(colored(":)", "green"))
    elif score < 0.0:
        print(colored(":(", "red"))
    else:
        print(colored(":|", "yellow"))


if __name__ == "__main__":
    main()
